# Canvas
CANVAS_WIDTH = 800
CANVAS_HEIGHT = 800

# Viewport
VIEWPORT_WIDTH = 1
VIEWPORT_HEIGHT = 1
PROJECTION_PLANE_D = 1

# Colors
BACKGROUND_COLOR = (0, 0, 0)

# Walls and Triangles small value
EPSILON = 1e-6